# user_info/urls.py

# Importing necessary modules and classes
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserInfoViewSet

# Creating a DefaultRouter to handle the viewset's URL routing
router = DefaultRouter()
router.register(r'user', UserInfoViewSet, basename='user')

# Defining the URL patterns for the app
urlpatterns = [
    # Including the URLs generated by the router
    path('', include(router.urls)),
]
